### ISSUE TITLE
Zero pool owners is a valid case, correct?

### ISSUE THREAD

**Issue by vantuz-subhuman** [input-output-hk/fm-ledger-rules#272]
Hello! Just to make it extra clear and sure. Spec says the pools owners is a powerset of hashes, which means 0 owners is also a valid case, right?

https://github.com/input-output-hk/fm-ledger-rules/blob/64c023b51ac9a92fb98b97323f2c15e05e478be8/latex/delegation.tex#L145-L146

And in general, whenever the powerset is used - it always means "zero or more", unless explicitly specified otherwise, right?

Thank you! )

**Comment by JaredCorduan** [comment]
Great question!

For the general question, yes indeed, the empty set is an element of every powerset (it's vacuously true). a fact which is notoriously good at causing problems. :)

Having no owners would be weird, but I don't think that that would cause any problems. If you had no owners, then the pool leader stake would be zero.  So the pool reward account would never get any rewards.  The members, however, could still get some rewards.

If the pledge in the pool reg cert was > 0, then this would mean that the pool as a whole (including members) would never get any rewards. (see the `maxP` variable in figure 37 of the `rewardOnePool` method).  Otherwise, if the pool reg cert set the pledge to zero, then it would be eligible for some rewards.  If you look at fig 35, at the `maxPool` method, then you'll see that if the pool set the pledge to zero, then `p_r` is zero, so `p'` is zero, and so they'd get `floor((R*sigma')/(1+a_0))` for their max possible rewards for the pool.  The members would get their slice of this pie.

Of course, the wallets would see this (either a pledge of zero or a stake pool not currently meeting its pledge), and not recommend such pools.

Thank you for asking the question and please keep 'em coming!!

**Comment by vantuz-subhuman** [comment]
Sounds good! Thank you! 🙂
