### ISSUE TITLE
Byron era: Make rules pertaining to the permissive BFT polymorphic

### ISSUE THREAD

**Issue by mdimjasevic** [input-output-hk/fm-ledger-rules#276]
Building upon issue #238 and a corresponding PR #239, the implementation of transition rules for the permissive BFT in the Byron era has to be updated so that the rules are constrained by the `Block b` type class from `Cardano.Spec.Consensus.Block` module instead of relying on the monomorphic `Block` type from the `Cardano.Spec.Chain.STS.Block` module.

This is all part of https://github.com/input-output-hk/ouroboros-network/issues/168.

**Comment by mdimjasevic** [comment]
@nc6, I'm planning to change the STS framework a bit. In particular, given that at the moment a specific type is expected as a signal for an STS, I'm planning to change that to a class constraint. For example, the CHAIN STS's signal wouldn't be the `Cardano.Spec.Chain.STS.Block.Block` type, but instead the signal would be constrained by the `Cardano.Spec.Consensus.Block.Block` class. Does that sound reasonable to you?

I started making changes along these lines, but then there's a whole snowball effect. For example, the first change to be made is in what is a signal of an `STS`:

```haskell
class ( Eq (PredicateFailure a)
      , Show (PredicateFailure a)
      )
  => STS a where
  ...
  type family Signal a :: * -> Constraint
  ...
```

This then made me to change the transition rule context from a newtype wrapping an environment, a state and a signal to this:

```haskell
-- | Context available to transition rules.
data TRC sts sig where
  TRC :: Signal sts sig => (Environment sts, State sts, sig) -> TRC sts sig
```
Does it make sense for a `TRC` to be parameterised by a signal? This change then triggers many more changes further down the line.

**Comment by nc6** [comment]
So, this could make sense, but I'm a little sceptical of the value. Such a block constraint is likely to be very constrained, since we rely a lot on the internal details. And part of such a constraint would require that e.g. we are able to extract the UTxO in the precise format used in the executable spec. I can't imagine we'd end up with very many instances for such a class, which limits the usefulness of making it one.

As an alternative, if the blocks _are_ suitably equivalent, we could just pre-process them to create the `Block` type, which is after all meant to represent the most basic block needed for implementation of the spec.

**Comment by nc6** [comment]
cc @edsko if you think there are good arguments the other way

**Comment by edsko** [comment]
No no, we certainly shouldn't need to abstract over stuff like the UTxO, delegation, whatever. We just need to make sure that the _consensus_ aspect is separated out. We should be able to run PermBFT with a different type of block and a different type of ledger, since PermBFT is independent from the ledger. I'd not expect to be able to compute the entire ledger on a different type of block; that would likely not be very useful, since you'd end up with constraints for all parts of the blocks and then might as well just require the very block type that the ledger rules require.

**Comment by edsko** [comment]
@nc6 @mdimjasevic This is the same consensus/ledger split we discussed previously, no?

**Comment by mdimjasevic** [comment]
> @nc6 @mdimjasevic This is the same consensus/ledger split we discussed previously, no?

Yes.

Where do I go from here?

**Comment by edsko** [comment]
We need to make sure that the consensus part of the rules is independent from the ledger part of the rules, and that the consensus part (but not the ledger part) is polymorphic enough.

**Comment by mdimjasevic** [comment]
As we discussed it earlier today, instead of making the rules polymorphic by making their signals a constraint rather than a type, I'm simply providing a function that converts a polymorphic block as given by a type class into the concrete block type used in `cs-blockchain`.
